name: provider_shopper
description: A shopping app sample that uses Provider for state management.
# publish_to: none
publish_to: https://psazuse.jfrog.io/artifactory/api/pub/krishnam-pub-virtual/
homepage: https://jfrog.com

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  provider: ^6.0.2
  window_size:
    # JFrog doc to setup VCS repo https://jfrog.com/help/r/jfrog-artifactory-documentation/vcs-repositories
    git:  # curl -u<UserName>:<ACCESS_TOKEN> -XGET https://psazuse.jfrog.io/artifactory/api/vcs/branches/krishnam-github-remote/<USER_ORG>/<REPO>
      # All Branches:: https://psazuse.jfrog.io/artifactory/api/vcs/branches/krishnam-github-remote/<USER_ORG>/<REPO>
      # Branch URL:: https://psazuse.jfrog.io/artifactory/api/vcs/downloadBranch/krishnam-github-remote/<USER_ORG>/<REPO>/<BRANCH_NAME>
      # url: https://github.com/google/flutter-desktop-embedding.git
      url:  https://psazuse.jfrog.io/artifactory/api/vcs/downloadBranch/krishnam-github-remote/google/flutter-desktop-embedding/main
      path: plugins/window_size

dev_dependencies:
  # analysis_defaults:
  #   path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
